server:
  port: 10070
  servlet:
    context-path: /baozhang

spring:
  data:
    mongodb:
      uri: mongodb://47.95.14.192:27017/
      database: baozhang
  redis:
    host: 47.95.14.192
    port: 6379
    timeout: 6000s
    password: root
  mail:
    host: smtp.163.com
    username: sugusron@163.com
    password: V0FORy4uMTk5NDA1MDU=
    default-encoding: UTF-8

mail:
  fromMail:
    addr: sugusron@163.com